### ISSUE TITLE
Specs should be written in markdown instead of Rich Text Format.

### ISSUE THREAD

**Issue by dhruvin2910** [Learnovate/Library-Portal#2]
Since the project is over GitHub and `markdown` is officially supported by GitHub (see [GFM](https://help.github.com/articles/github-flavored-markdown/)), specs should be written in that format, as we do in case of `README.md`, so it can be read online.

**Comment by buzz2vatsal** [comment]
Ohkay, Thanks! was helpful (Y)

**Comment by Arvindiyer** [comment]
@buzz2vatsal  @dhruvin2910  Wanted to inform you that use markdown files instead of `.txt` file.

**Comment by buzz2vatsal** [comment]
Implemented
