### ISSUE TITLE
Task List not as required in README.md

### ISSUE THREAD

**Issue by buzz2vatsal** [Learnovate/Library-Portal#3]
The square checkboxes aren't showing in the readme.md. I might be missing something. Suggest @Arvindiyer @dhruvin2910

**Comment by dhruvin2910** [comment]
Check out this :
https://github.com/github/markup/issues/208#issuecomment-24927799

**Comment by dhruvin2910** [comment]
Remove (3) back-quotes from that checklist block (before and after the checklist).

**Comment by buzz2vatsal** [comment]
Thanks for the suggestion. For Tasklist I was trying to use both functions as a time so got stuck

**Comment by buzz2vatsal** [comment]
Thanks for the suggestion. For Tasklist I was trying to use both functions as a time so got stuck
