### ISSUE TITLE
Where to check Network/Flow of branches ?

### ISSUE THREAD

**Issue by buzz2vatsal** [Learnovate/Library-Portal#5]
I want to check network of branch and sub-branch ie flow chart of branching system. Can u explain where to find? I also want to learn to "pull and merge" which I will do in development branch for features as soon as members upload the suggestions.

**Comment by Arvindiyer** [comment]
You can look into the official documentation of github support
https://help.github.com/articles/about-repository-graphs/

For pull and merge i hope this helps 
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
